import "./stylesheets/main.css";
import "./global.css";

import Menu from './components/menu'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{margin: '0'}}>
        <Menu></Menu>

        {children}</body>
    </html>
  );
}
